version: 2.1
orbs:
  gradle: circleci/gradle@1.0.11
workflows:
  build-and-publish-snapshot:
    jobs:
      - gradle/test:
          reports_path: build/test-reports
          test_results_path: build/test-results
          context: fng-gradle-snapshot
      - gradle/run:
          command: publish
          filters:
            branches:
              only: bleeding
          context: fng-gradle-snapshot
      - gradle/run:
          command: publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+-rc\.\d+$/
            context: fng-gradle-preRelease
      - gradle/run:
          command: publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          context: fng-gradle-release
